ALTER TABLE voice_session
    ADD COLUMN IF NOT EXISTS muted BIT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS deafened BIT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS suppressed BIT(1) NOT NULL DEFAULT 0;
